#!/usr/bin/env python3
"""
Build the Dhan Cloud upload files from the tested sources (Phase 6).

  python3 cloud/build_bundle.py            # (re)write cloud/dist/
  python3 cloud/build_bundle.py --check    # exit 1 if cloud/dist/ is out of date

Outputs (GENERATED; never edit by hand, a test fails on drift):
  cloud/dist/multi/   main.py + bx_*.py + requirements.txt   (flat, no package)
  cloud/dist/single/  sensex_observer.py                     (one file, stdlib only)

Both are built from engine/sensex/*.py, engine/refresh_table.py and
cloud/src/cloud_main.py by mechanical rewriting only:
  multi:  relative imports -> flat `bx_` imports;
  single: internal imports removed, modules concatenated in dependency order;
          a top-level name bound differently by two modules is renamed in the
          module(s) nobody imports it from (checked; scopes respected).
No exec/eval, no dynamic import, no network in either output.
"""

from __future__ import annotations

import ast
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ENGINE = ROOT / "engine"
DIST = ROOT / "cloud" / "dist"
SRC_MAIN = ROOT / "cloud" / "src" / "cloud_main.py"
STAGE_A = ROOT / "parity" / "stage_a" / "s21Sep"

# Dependency order (each module only uses names from modules before it).
MODULES = ["jscompat", "errors", "pricing", "gate", "normalize", "integrity", "pricing_bridge", "levels",
           "expiries", "scan", "dhan_client", "validation", "session", "instruments", "observation",
           "paper", "fastpoll", "scanner", "recording"]
HEADER = ("# GENERATED by cloud/build_bundle.py from {src} - do not edit; edit the source and rebuild.\n"
          "# READ-ONLY observation program: no order, position, login or token-renewal code.\n")


# ------------------------------------------------------------- self-test data
def selftest_data() -> dict:
    """Embedded MOCK snapshot (Stage A s21Sep) plus the table the TESTED
    package produces on it; the Cloud VALIDATE mode must reproduce it."""
    sys.path.insert(0, str(ENGINE))
    from sensex.mock_dhan import load_scenario, mock_scanner  # noqa: E402
    from sensex.dhan_client import Redactor  # noqa: E402
    bodies, ref = load_scenario("s21Sep")
    sc, _ = mock_scanner(Redactor(), "s21Sep")
    rec = sc.run_once()
    assert rec["status"] == "OK", rec
    at = datetime.fromtimestamp(ref["receipts"]["chainMs"] / 1000, timezone.utc)
    return {"note": "MOCK DATA (Stage A s21Sep) - not market data", "bodies": bodies,
            "receipts": {"/optionchain": ref["receipts"]["chainMs"], "/marketfeed/quote": ref["receipts"]["futuresMs"],
                         "/optionchain/expirylist": ref["receipts"]["chainMs"],
                         "/charts/intraday": ref["receipts"]["chainMs"]},
            "strikes": ref["strikes"], "futuresSecurityId": "844615", "futuresExpiry": "2026-09-24",
            "clockUtc": at.isoformat(), "expectedTable": rec["table"]}


def selftest_source() -> str:
    return ('"""Embedded MOCK self-test snapshot (Stage A s21Sep). Not market data."""\n\n'
            "SELFTEST = " + repr(selftest_data()) + "\n")


# ---------------------------------------------------------------------- multi
_REL = re.compile(r"^(\s*)from \.(\w+) import", re.M)
_PKG = re.compile(r"^(\s*)from sensex\.(\w+) import", re.M)


def to_flat(text: str) -> str:
    text = _REL.sub(r"\1from bx_\2 import", text)
    text = _PKG.sub(r"\1from bx_\2 import", text)
    return text.replace("import refresh_table as rt", "import bx_refresh_table as rt")


def build_multi() -> dict:
    out = {}
    for m in MODULES:
        out["bx_%s.py" % m] = HEADER.format(src="engine/sensex/%s.py" % m) + to_flat(
            (ENGINE / "sensex" / ("%s.py" % m)).read_text())
    out["bx_refresh_table.py"] = HEADER.format(src="engine/refresh_table.py") + (ENGINE / "refresh_table.py").read_text()
    out["bx_selftest_data.py"] = HEADER.format(src="parity/stage_a/s21Sep") + selftest_source()
    out["main.py"] = HEADER.format(src="cloud/src/cloud_main.py") + to_flat(SRC_MAIN.read_text())
    out["requirements.txt"] = "# Standard library only. No packages are required.\n"
    return out


# --------------------------------------------------------------------- single
def _internal(node) -> str | None:
    """Module name an internal import refers to, else None."""
    if isinstance(node, ast.ImportFrom):
        if node.level:
            return node.module
        if node.module and node.module.startswith("sensex."):
            return node.module.split(".", 1)[1]
        if node.module == "bx_selftest_data":
            return "selftest_data"
    return None


def _bindings(mod: str, tree) -> dict:
    """Top-level name -> identity of what it is bound to."""
    b = {}
    for n in tree.body:
        if isinstance(n, ast.ImportFrom):
            if n.module == "__future__":
                continue
            src = _internal(n)
            for a in n.names:
                b[a.asname or a.name] = ("def", src, a.name) if src else ("from", n.module, a.name)
        elif isinstance(n, ast.Import):
            for a in n.names:
                b[a.asname or a.name.split(".")[0]] = ("mod", a.name if a.asname else a.name.split(".")[0])
        elif isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            b[n.name] = ("def", mod, n.name)
        elif isinstance(n, (ast.Assign, ast.AnnAssign)):
            for t in (n.targets if isinstance(n, ast.Assign) else [n.target]):
                for x in ast.walk(t):
                    if isinstance(x, ast.Name):
                        b[x.id] = ("def", mod, x.id)
    return b


class _Renamer(ast.NodeTransformer):
    def __init__(self, mapping):
        self.map = mapping

    def _locals(self, fn) -> set:
        a = fn.args
        names = {x.arg for x in a.args + a.kwonlyargs + a.posonlyargs}
        names |= {x.arg for x in (a.vararg, a.kwarg) if x}
        glob = set()
        for x in ast.walk(fn):
            if isinstance(x, ast.Name) and isinstance(x.ctx, ast.Store):
                names.add(x.id)
            elif isinstance(x, ast.Global):
                glob |= set(x.names)
            elif isinstance(x, (ast.Import, ast.ImportFrom)):
                names |= {(y.asname or y.name.split(".")[0]) for y in x.names}
        return names - glob

    def visit_FunctionDef(self, node):
        if node.name in self.map:
            node.name = self.map[node.name]
        shadow = self._locals(node) & set(self.map)
        if shadow:
            for d in node.decorator_list + node.args.defaults + node.args.kw_defaults:
                if d is not None:
                    self.visit(d)
            inner = _Renamer({k: v for k, v in self.map.items() if k not in shadow})
            node.body = [inner.visit(s) for s in node.body]
            if node.returns is not None:
                node.returns = self.visit(node.returns)
            return node
        return self.generic_visit(node)

    visit_AsyncFunctionDef = visit_FunctionDef

    def visit_ClassDef(self, node):
        if node.name in self.map:
            node.name = self.map[node.name]
        return self.generic_visit(node)

    def visit_Name(self, node):
        if node.id in self.map:
            node.id = self.map[node.id]
        return node

    def visit_Global(self, node):
        node.names = [self.map.get(n, n) for n in node.names]
        return node


class _StripInternal(ast.NodeTransformer):
    """Drop internal imports; `import refresh_table as rt` -> `rt = _BX_RT`."""

    def visit_ImportFrom(self, node):
        if node.module == "__future__" or _internal(node) is not None:
            return None
        return node

    def visit_Import(self, node):
        if [a.name for a in node.names] == ["refresh_table"]:
            return ast.copy_location(ast.Assign(targets=[ast.Name(node.names[0].asname or "refresh_table", ast.Store())],
                                                value=ast.Name("_BX_RT", ast.Load()), lineno=node.lineno), node)
        return node


def _rename_imports(tree, mapping):
    """Rename stdlib import aliases (`from datetime import time` -> `... as _bx_x__time`)."""
    for n in ast.walk(tree):
        if isinstance(n, (ast.Import, ast.ImportFrom)):
            for a in n.names:
                bound = a.asname or a.name.split(".")[0]
                if bound in mapping:
                    if isinstance(n, ast.Import) and "." in a.name and not a.asname:
                        raise SystemExit("cannot rename dotted import %s" % a.name)
                    a.asname = mapping[bound]


def build_single() -> str:
    sources = [("refresh_table", "engine/refresh_table.py", (ENGINE / "refresh_table.py").read_text())]
    sources += [(m, "engine/sensex/%s.py" % m, (ENGINE / "sensex" / ("%s.py" % m)).read_text()) for m in MODULES]
    sources += [("selftest_data", "parity/stage_a/s21Sep", selftest_source()),
                ("main", "cloud/src/cloud_main.py", SRC_MAIN.read_text())]
    trees = {m: ast.parse(t) for m, _, t in sources}
    binds = {m: _bindings(m, trees[m]) for m in trees}

    def resolve(ident):
        seen = 0
        while ident[0] == "def" and ident[1] != "" and ident[2] in binds.get(ident[1], {}) \
                and binds[ident[1]][ident[2]] != ident and seen < 20:
            ident, seen = binds[ident[1]][ident[2]], seen + 1
        return ident

    # names bound to different things in different modules
    by_name = {}
    for m, b in binds.items():
        for name, ident in b.items():
            by_name.setdefault(name, {})[m] = resolve(ident)
    imported_from = {}
    for m, b in binds.items():
        for name, ident in b.items():
            if ident[0] == "def" and ident[1] != m:
                imported_from.setdefault(name, set()).add(resolve(ident))
    renames = {m: {} for m in trees}
    for name, per_mod in by_name.items():
        idents = set(per_mod.values())
        if len(idents) < 2:
            continue
        keep = imported_from.get(name, set())
        if len(keep) > 1:
            raise SystemExit("name %r imported with %d different meanings; cannot flatten" % (name, len(keep)))
        keep = next(iter(keep)) if keep else per_mod[next(m for m, _, _ in sources if m in per_mod)]
        for m, ident in per_mod.items():
            if ident != keep:
                renames[m][name] = "_bx_%s__%s" % (m, name)

    rt_attrs = sorted({n.attr for n in ast.walk(trees["scan"]) if isinstance(n, ast.Attribute)
                       and isinstance(n.value, ast.Name) and n.value.id == "rt"})
    parts = ['"""\nSENSEX read-only observation scanner for Dhan Cloud - SINGLE-FILE build.\n'
             "GENERATED by cloud/build_bundle.py; do not edit. Configure the CONFIG block in the\n"
             "`main` section below (search for \"CONFIG\").\n\nREAD-ONLY: no order, position, login or "
             'token-renewal code.\n"""\n\nfrom __future__ import annotations\n']
    for m, label, _ in sources:
        tree = trees[m]
        if renames[m]:
            _rename_imports(tree, renames[m])
            tree = _Renamer(renames[m]).visit(tree)
        tree = ast.fix_missing_locations(_StripInternal().visit(tree))
        body = ast.unparse(tree)
        if m == "main":   # keep the CONFIG block with its comments, verbatim
            raw = SRC_MAIN.read_text()
            a, b = raw.index("# ============================== CONFIG"), raw.index("# =======================", raw.index("# ============================== CONFIG") + 10)
            b = raw.index("\n", b) + 1
            body = "# " + "=" * 70 + "\n" + raw[a:b] + "\n" + _drop_config_assigns(body)
        parts.append("\n# %s\n# module: %s\n# %s\n%s\n" % ("-" * 70, label, "-" * 70, body))
        if m == "refresh_table":
            parts.append("import types as _bx_types\n_BX_RT = _bx_types.SimpleNamespace(%s)\n"
                         % ", ".join("%s=%s" % (a, a) for a in rt_attrs))
    return "".join(parts)


def _drop_config_assigns(body: str) -> str:
    """The CONFIG block is re-inserted verbatim (with comments); drop its unparsed copy."""
    raw = SRC_MAIN.read_text()
    a = raw.index("# ============================== CONFIG")
    b = raw.index("# =======================", a + 10)
    names = {t.id for n in ast.parse(raw[a:b]).body if isinstance(n, ast.Assign) for t in n.targets
             if isinstance(t, ast.Name)}
    tree = ast.parse(body)
    tree.body = [n for n in tree.body if not (isinstance(n, ast.Assign) and len(n.targets) == 1
                                              and isinstance(n.targets[0], ast.Name) and n.targets[0].id in names)]
    return ast.unparse(tree)


def build() -> dict:
    files = {"multi/" + k: v for k, v in build_multi().items()}
    files["single/sensex_observer.py"] = build_single()
    return files


def main(argv) -> int:
    files = build()
    if "--check" in argv:
        stale = [k for k, v in files.items() if not (DIST / k).exists() or (DIST / k).read_text() != v]
        extra = [str(p.relative_to(DIST)) for p in DIST.rglob("*") if p.is_file()
                 and str(p.relative_to(DIST)) not in files and "__pycache__" not in str(p)]
        if stale or extra:
            print("cloud/dist is out of date: %s %s" % (stale, extra))
            return 1
        print("cloud/dist is up to date (%d files)" % len(files))
        return 0
    for k, v in files.items():
        p = DIST / k
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(v)
    print("wrote %d files under %s" % (len(files), DIST))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
